### ISSUE TITLE
App isn't finding public folder?

### ISSUE THREAD

**Issue by shootTheLuck** [rooseveltframework/generator-roosevelt#319]
Hi,

I'm trying to run the example (boilerplate)  app created with npx mkroosevelt.  It runs and shows 

> My Roosevelt Sample App
> 
> Hi! I'm a variable trickling down through the MVC structure!
> 
> Here's a silly picture of Teddy Roosevelt:

 but it doesn't find the picture of Teddy Roosevelt or run the css or js.   The browser, for instance says:

> Loading failed for the <script> with source “http://localhost:43711/js/main.js

and the app logs say:

> GET /js/main.js HTTP/1.1" 404 663

I'd love to try Roosevelt further.  Please let me know if I'm missing something or if you'd like more information.  Thanks!

**Comment by Autre31415** [comment]
If you're starting your app in production mode via `npm start` by default static assets will not be hosted which is why you wouldn't see the css/js/images load. The default production mode settings in Roosevelt presume that your static assets are being hosted by a proxy. There are a handful of ways to get around this behavior:
- Starting your app in development mode via `npm run dev`.
- Starting your app in production mode with an additional `--host-public` flag via `npm run proddev`.
- Adding `"alwaysHostPublic": true` to `rooseveltConfig.json`.

**Comment by shootTheLuck** [comment]
Oh man, it says that right in the terminal too.  Thanks so much.
